# tasks file for rsyslog
---
- name: install
  apt:
    name: rsyslog
    state: latest
    update_cache: true
    cache_valid_time: 3600
  tags:
    - configuration
    - rsyslog
    - rsyslog-install

- name: fix dir permissions
  # workaround for: https://bugs.launchpad.net/ubuntu/+source/rsyslog/+bug/1256695/comments/5
  file:
    path: /var/log
    owner: root
    group: syslog
    mode: 0775
  tags:
    - configuration
    - rsyslog
    - rsyslog-configuration
    - rsyslog-configuration-permissions

- name: update specific configuration files
  template:
    src: etc/rsyslog.d/rsyslog.conf.j2
    dest: "/etc/rsyslog.d/{{ item.key }}.conf"
    validate: "{{ 'rsyslogd -N1 -f %s' if item.value.validate | default(true) else 'true %s' }}"
    owner: root
    group: root
    mode: 0440
  with_dict: rsyslog_rsyslog_d_files
  when: item.value.state | default('present') == 'present'
  notify: restart rsyslog
  tags:
    - configuration
    - rsyslog
    - rsyslog-configuration
    - rsyslog-configuration-rsyslog-d

- name: remove configurations
  file:
    dest: "/etc/rsyslog.d/{{ item.key }}.conf"
    state: absent
  with_dict: rsyslog_rsyslog_d_files
  when: item.value.state | default('present') == 'absent'
  notify: restart rsyslog
  tags:
    - configuration
    - rsyslog
    - rsyslog-configuration
    - rsyslog-configuration-rsyslog-d

- name: update global configuration file
  template:
    src: etc/rsyslog.conf.j2
    dest: /etc/rsyslog.conf
    validate: "rsyslogd -N1 -f %s"
    owner: root
    group: root
    mode: 0440
  notify: restart rsyslog
  tags:
    - configuration
    - rsyslog
    - rsyslog-configuration
    - rsyslog-configuration-rsyslog
